apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/runtime-spine

patches:
  - target:
      kind: Deployment
      name: runtime-spine
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: disabled
