import { type EditableUIDocument } from "./uiDocumentModel";
export type UIDocumentDiffOperationKind = "nodeAdded"|"nodeRemoved"|"nodeMoved"|"nodeUpdated"|"pageAdded"|"pageRemoved"|"themeUpdated"|"bindingUpdated"|"layoutUpdated"|"styleUpdated"|"textUpdated";
export type UIDocumentDiffOperation = { kind: UIDocumentDiffOperationKind; nodeId?: string; pageId?: string; before?: unknown; after?: unknown };
export type UIDocumentDiff = { operations: UIDocumentDiffOperation[]; changedNodeIds: string[]; changedPageIds: string[] };
const stable=(v:unknown)=>JSON.stringify(v,Object.keys((v as any)||{}).sort());
export function createUIDocumentDiff(before: EditableUIDocument, after: EditableUIDocument): UIDocumentDiff { const ops: UIDocumentDiffOperation[]=[]; const changedNodeIds=new Set<string>(); const changedPageIds=new Set<string>();
 const bp=new Map(before.pages.map(p=>[p.id,p])); const ap=new Map(after.pages.map(p=>[p.id,p]));
 for (const id of [...bp.keys()].sort()) if(!ap.has(id)){ops.push({kind:"pageRemoved",pageId:id}); changedPageIds.add(id);} for (const id of [...ap.keys()].sort()) if(!bp.has(id)){ops.push({kind:"pageAdded",pageId:id}); changedPageIds.add(id);} 
 if (stable(before.theme)!==stable(after.theme)) ops.push({kind:"themeUpdated",before:before.theme,after:after.theme});
 for (const id of [...bp.keys()].filter(i=>ap.has(i)).sort()){ const b=bp.get(id)!; const a=ap.get(id)!; const bn=new Set(Object.keys(b.nodes)); const an=new Set(Object.keys(a.nodes));
 for(const nid of [...bn].sort()) if(!an.has(nid)){ops.push({kind:"nodeRemoved",pageId:id,nodeId:nid}); changedNodeIds.add(nid); changedPageIds.add(id);} for(const nid of [...an].sort()) if(!bn.has(nid)){ops.push({kind:"nodeAdded",pageId:id,nodeId:nid}); changedNodeIds.add(nid); changedPageIds.add(id);} 
 for(const nid of [...bn].filter(n=>an.has(n)).sort()){ const x=b.nodes[nid], y=a.nodes[nid]; if(x.parentId!==y.parentId){ops.push({kind:"nodeMoved",pageId:id,nodeId:nid}); changedNodeIds.add(nid);} if(stable(x.props)!==stable(y.props)) {ops.push({kind:"nodeUpdated",pageId:id,nodeId:nid}); if(String(x.props?.text??"")!==String(y.props?.text??"")) ops.push({kind:"textUpdated",pageId:id,nodeId:nid}); changedNodeIds.add(nid);} if(stable(x.style)!==stable(y.style)){ops.push({kind:"styleUpdated",pageId:id,nodeId:nid}); changedNodeIds.add(nid);} if(stable(x.layout)!==stable(y.layout)){ops.push({kind:"layoutUpdated",pageId:id,nodeId:nid}); changedNodeIds.add(nid);} if(stable(x.bindings)!==stable(y.bindings)||stable(x.actionBindings)!==stable(y.actionBindings)||stable(x.formBindings)!==stable(y.formBindings)){ops.push({kind:"bindingUpdated",pageId:id,nodeId:nid}); changedNodeIds.add(nid);}  }
 }
 return {operations:ops, changedNodeIds:[...changedNodeIds].sort(), changedPageIds:[...changedPageIds].sort()}; }
export function summarizeUIDocumentDiff(diff: UIDocumentDiff): string { const counts = diff.operations.reduce((a,o)=>(a[o.kind]=(a[o.kind]??0)+1,a),{} as Record<string,number>); return Object.keys(counts).sort().map(k=>`${k}:${counts[k]}`).join(", "); }
export function validateUIDocumentDiff(diff: Partial<UIDocumentDiff>): {valid:boolean;issues:string[]} { const issues:string[]=[]; if(!Array.isArray(diff.operations)) issues.push("operations missing"); if(!Array.isArray(diff.changedNodeIds)) issues.push("changedNodeIds missing"); if(!Array.isArray(diff.changedPageIds)) issues.push("changedPageIds missing"); return {valid:issues.length===0,issues}; }
