import crypto from "crypto";
import { UI_LIVE_BUILDER_ORCHESTRATION_CAVEAT, UI_LIVE_BUILDER_ORCHESTRATION_STAGE_IDS, type UILiveBuilderOrchestrationDependency, type UILiveBuilderOrchestrationIssue, type UILiveBuilderOrchestrationPlan, type UILiveBuilderOrchestrationResult, type UILiveBuilderOrchestrationStage, type UILiveBuilderOrchestrationStageId } from "./uiLiveBuilderOrchestrationModel";
const sortedUniq=(v:string[]=[])=>[...new Set(v.filter(Boolean))].sort(); const risk=(r:any)=>(r==="high"||r==="medium")?r:"low";
export function createUILiveBuilderOrchestrationPlan(input:any): UILiveBuilderOrchestrationResult { const issues:UILiveBuilderOrchestrationIssue[]=[]; try { if(!input||typeof input!=="object") throw new Error("malformed input");
const s:any={command:input.commandResult,"target-resolution":input.targetResolutionResult,"ui-mutation":input.uiMutationResult,"direct-manipulation":input.directManipulationResult,"app-structure":input.appStructureResult,"source-identity":input.sourceIdentityResult,"multi-file":input.multiFileEditPlan,"full-project":input.fullProjectGenerationPlan,"design-system":input.designStylePlan,"data-state-api":input.dataStateApiWiringPlan,"reliability-repair":input.reliabilityRepairPlan,"scalability-performance":input.scalabilityPerformancePlan,"ux-control":input.uxControlPlan,"export-deploy":input.exportDeployPlan,"platform-builder":input.platformBuilderPlan};
const present=UI_LIVE_BUILDER_ORCHESTRATION_STAGE_IDS.filter((id)=>s[id]); const deps:UILiveBuilderOrchestrationDependency[]=[]; const add=(f:UILiveBuilderOrchestrationStageId,t:UILiveBuilderOrchestrationStageId)=>{if(present.includes(f)&&present.includes(t)) deps.push({fromStageId:f,toStageId:t});};
add("command","target-resolution");add("target-resolution","ui-mutation");add("ui-mutation","direct-manipulation");add("ui-mutation","app-structure"); if(present.includes("source-identity")) ["ui-mutation","app-structure","direct-manipulation"].forEach((f)=>add(f as any,"source-identity")); add("source-identity","multi-file"); add("multi-file","full-project"); add("app-structure","full-project");
if(present.includes("design-system")){ if(present.includes("full-project")) add("full-project","design-system"); else if(present.includes("source-identity")) add("source-identity","design-system"); else add("multi-file","design-system");}
if(present.includes("data-state-api")){ if(present.includes("full-project")) add("full-project","data-state-api"); else add("design-system","data-state-api");}
if(present.includes("reliability-repair")){ if(present.includes("full-project")) add("full-project","reliability-repair"); if(present.includes("data-state-api")) add("data-state-api","reliability-repair"); if(present.includes("multi-file")) add("multi-file","reliability-repair");}
if(present.includes("scalability-performance")){ if(present.includes("reliability-repair")) add("reliability-repair","scalability-performance"); else if(present.includes("full-project")) add("full-project","scalability-performance"); else add("multi-file","scalability-performance");}
if(present.includes("ux-control")){ if(present.includes("scalability-performance")) add("scalability-performance","ux-control"); else add("reliability-repair","ux-control");}
if(present.includes("export-deploy")){ ["full-project","scalability-performance","reliability-repair","ux-control"].forEach((f)=>add(f as any,"export-deploy")); }
if(present.includes("platform-builder")){ if(present.includes("export-deploy")) add("export-deploy","platform-builder"); else if(present.includes("scalability-performance")) add("scalability-performance","platform-builder"); else add("full-project","platform-builder"); }
const inDeg:Record<string,number>={}; present.forEach((i)=>inDeg[i]=0); deps.forEach((d)=>inDeg[d.toStageId]++); const q=present.filter((i)=>inDeg[i]===0).sort(); const ordered:UILiveBuilderOrchestrationStageId[]=[]; while(q.length){const n=q.shift() as any; ordered.push(n); deps.filter((d)=>d.fromStageId===n).forEach((d)=>{inDeg[d.toStageId]--; if(inDeg[d.toStageId]===0) q.push(d.toStageId);}); q.sort(); }
const upstreamPlanIds:Record<string,string>={}; const stages:UILiveBuilderOrchestrationStage[]=present.map((id)=>{const p=s[id]||{}; const up=p.sourceIdentityId||p.multiFilePlanId||p.fullProjectPlanId||p.stylePlanId||p.wiringPlanId||p.repairPlanId||p.scalabilityPlanId||p.uxControlPlanId||p.exportDeployPlanId||p.platformBuilderPlanId||p.planId; if(up) upstreamPlanIds[id]=up; return {id,status:p.blockedReasons?.length?"blocked":"ready",riskLevel:risk(p.riskLevel),requiresManualReview:!!p.requiresManualReview,blockedReasons:sortedUniq(p.blockedReasons||[]),caveats:sortedUniq([p.caveat].filter(Boolean)),upstreamPlanId:up,changedFiles:sortedUniq(p.changedFiles||[]),affectedFilePaths:sortedUniq(p.affectedFilePaths||[])};});
let blockedReasons=sortedUniq(stages.flatMap((x)=>x.blockedReasons)); const caveats=sortedUniq([...stages.flatMap((x)=>x.caveats),UI_LIVE_BUILDER_ORCHESTRATION_CAVEAT]);
const opts=input.options||{}; const sourceIdentity=s["source-identity"]; const sourceOk=!!sourceIdentity && !["low","stale","missing"].includes(String(sourceIdentity?.confidence??"high"));
if(opts.requireSourceIdentity && !sourceIdentity) blockedReasons.push("required stage missing: source-identity"); if(sourceIdentity && !sourceOk) blockedReasons.push("source identity low/stale/missing confidence"); if(opts.requireRollbackProof && !opts.guardedApplyProof?.rollbackVerified) blockedReasons.push("rollback proof required but missing"); if(opts.requireExportPlan && !s["export-deploy"]) blockedReasons.push("required stage missing: export-deploy"); if(opts.requirePlatformPlan && !s["platform-builder"]) blockedReasons.push("required stage missing: platform-builder"); if(opts.allowSourceApply && (!opts.guardedApplyProof?.rollbackVerified || !opts.guardedApplyProof?.sourceIdentityVerified)) blockedReasons.push("allowSourceApply blocked without guarded proof"); if(opts.allowExportExecution) blockedReasons.push("allowExportExecution blocked"); if(opts.allowPlatformExecution) blockedReasons.push("allowPlatformExecution blocked");
blockedReasons=sortedUniq(blockedReasons);
const childHigh=stages.some((x)=>x.riskLevel==="high"); const childManual=stages.some((x)=>x.requiresManualReview); const requiresManualReview=childManual||blockedReasons.length>0||!sourceOk&&!!sourceIdentity||!!opts.requireSourceIdentity&&!sourceIdentity; const riskLevel=(childHigh||requiresManualReview)?"high":"low";
const changedFiles=sortedUniq(stages.flatMap((x)=>x.changedFiles)); const affectedFilePaths=sortedUniq(stages.flatMap((x)=>x.affectedFilePaths));
const readyForExportPlanning=(!!s["full-project"]||!!s["multi-file"]) && !blockedReasons.some((r)=>r.includes("export")); const readyForPlatformPlanning=!!s["export-deploy"] && !blockedReasons.some((r)=>r.includes("platform"));
const readyForSourceApply=!requiresManualReview&&riskLevel!=="high"&&sourceOk&&(!opts.requireRollbackProof||!!opts.guardedApplyProof?.rollbackVerified)&&!!opts.guardedApplyProof?.sourceIdentityVerified;
const executionBlocked=present.includes("export-deploy")||present.includes("platform-builder")?true:true;
const orchestrationPlanId=`orchestration-${crypto.createHash("sha256").update(JSON.stringify({present,deps,upstreamPlanIds,changedFiles,affectedFilePaths,blockedReasons})).digest("hex").slice(0,16)}`;
const plan:UILiveBuilderOrchestrationPlan={orchestrationPlanId,stages,dependencies:deps,gates:[{gateId:"execution-blocked",passed:executionBlocked,reason:"dry-run only"}],orderedStageIds:ordered,upstreamPlanIds,affectedFilePaths,changedFiles,blockedReasons,caveats,riskLevel,requiresManualReview,readyForSourceApply,readyForExportPlanning,readyForPlatformPlanning,executionBlocked,caveat:UI_LIVE_BUILDER_ORCHESTRATION_CAVEAT};
return {status:requiresManualReview?"blocked":"planned",plan,issues}; } catch(e:any){issues.push({code:"MALFORMED_INPUT",message:String(e?.message||e),severity:"error"}); return {status:"blocked",issues,plan:{orchestrationPlanId:"orchestration-error",stages:[],dependencies:[],gates:[],orderedStageIds:[],upstreamPlanIds:{},affectedFilePaths:[],changedFiles:[],blockedReasons:["malformed input"],caveats:[UI_LIVE_BUILDER_ORCHESTRATION_CAVEAT],riskLevel:"high",requiresManualReview:true,readyForSourceApply:false,readyForExportPlanning:false,readyForPlatformPlanning:false,executionBlocked:true,caveat:UI_LIVE_BUILDER_ORCHESTRATION_CAVEAT}}; }}
