import { UI_LIVE_BUILDER_ORCHESTRATION_STAGE_IDS, type UILiveBuilderOrchestrationIssue, type UILiveBuilderOrchestrationPlan } from "./uiLiveBuilderOrchestrationModel";
const sortedUniq=(v:string[])=>[...new Set(v)].sort();
export function verifyUILiveBuilderOrchestrationGraph(plan:any,input?:any){ const issues:UILiveBuilderOrchestrationIssue[]=[]; try { if(!plan||typeof plan!=="object") throw new Error("malformed graph"); const p=plan as UILiveBuilderOrchestrationPlan; const ids=(p?.stages||[]).map((s:any)=>s.id); if(new Set(ids).size!==ids.length) issues.push({code:"DUPLICATE_STAGE",message:"duplicate stage ids",severity:"error"});
for(const d of p?.dependencies||[]) if(!ids.includes(d.fromStageId)||!ids.includes(d.toStageId)) issues.push({code:"MISSING_DEP",message:"dependency stage missing",severity:"error"});
if(sortedUniq(ids).join("|")!==sortedUniq(p?.orderedStageIds||[]).join("|") || (p?.orderedStageIds||[]).length!==ids.length) issues.push({code:"ORDERED_IDS_INVALID",message:"orderedStageIds must include all stages once",severity:"error"});
const idx=new Map((p?.orderedStageIds||[]).map((x:any,i:number)=>[x,i])); for(const d of p?.dependencies||[]) if((idx.get(d.fromStageId)??999)>(idx.get(d.toStageId)??-1)) issues.push({code:"DEPENDENCY_ORDER",message:"dependency order violated",severity:"error"});
const g:any={}; ids.forEach((i:string)=>g[i]=[]); (p?.dependencies||[]).forEach((d:any)=>g[d.fromStageId].push(d.toStageId)); const vis:any={},st:any={}; const dfs=(n:string)=>{vis[n]=1; st[n]=1; for(const m of g[n]||[]){ if(!vis[m]) dfs(m); else if(st[m]) issues.push({code:"CYCLE",message:"cycle detected",severity:"error"}); } st[n]=0;}; ids.forEach((n:string)=>{if(!vis[n]) dfs(n);});
if(JSON.stringify(p?.changedFiles||[])!==JSON.stringify(sortedUniq(p?.changedFiles||[]))) issues.push({code:"CHANGED_FILES_SORT",message:"changedFiles not sorted/deduped",severity:"error"});
if(JSON.stringify(p?.affectedFilePaths||[])!==JSON.stringify(sortedUniq(p?.affectedFilePaths||[]))) issues.push({code:"AFFECTED_FILES_SORT",message:"affectedFilePaths not sorted/deduped",severity:"error"});
if((ids.includes("export-deploy")||ids.includes("platform-builder")) && p?.executionBlocked!==true) issues.push({code:"EXECUTION_BLOCK",message:"executionBlocked must be true",severity:"error"});
for (const k of ["sourceIdentityId","multiFilePlanId","fullProjectPlanId","exportDeployPlanId","platformBuilderPlanId"]) { if(input?.[k] && !Object.values(p?.upstreamPlanIds||{}).includes(input[k])) issues.push({code:"UPSTREAM_ID",message:`missing upstream id preservation: ${k}`,severity:"error"}); }
return {valid:issues.length===0,issues}; } catch(e:any){ return {valid:false,issues:[{code:"MALFORMED_GRAPH",message:String(e?.message||e),severity:"error"}]}; }}
export const UILiveBuilderOrchestrationCanonicalStageIds = UI_LIVE_BUILDER_ORCHESTRATION_STAGE_IDS;
