import type { UIPlatformAssetRequirement, UIPlatformBuilderKind, UIPlatformCapability, UIPlatformFramework, UIPlatformManifestRequirement, UIPlatformTarget } from "./uiPlatformBuilderModel";

export function createUIPlatformCapabilityPlan(input: {targetPlatform:UIPlatformTarget; builderKind:UIPlatformBuilderKind; framework:UIPlatformFramework;}): {capabilities:UIPlatformCapability[]; requiredAssets:UIPlatformAssetRequirement[]; manifestRequirements:UIPlatformManifestRequirement[]} {
  const t=input.targetPlatform;
  const capabilities: UIPlatformCapability[]=[];
  if (t==="ios") capabilities.push({key:"mobile-runtime",detail:"mobile runtime"},{key:"icons",detail:"icons"},{key:"splash-screen",detail:"splash screen"},{key:"app-identifier",detail:"app identifier"},{key:"store-metadata",detail:"store metadata"},{key:"native-permissions",detail:"native permission declarations"},{key:"build-execution-blocked",detail:"simulator build execution blocked"});
  if (t==="android") capabilities.push({key:"mobile-runtime",detail:"mobile runtime"},{key:"launcher-icons",detail:"launcher icons"},{key:"adaptive-icon",detail:"adaptive icon"},{key:"package-name",detail:"package name"},{key:"store-metadata",detail:"store metadata"},{key:"permissions",detail:"permission declarations"},{key:"build-execution-blocked",detail:"emulator build execution blocked"});
  if (t==="mobile-web"||t==="desktop-web") capabilities.push({key:"web-runtime",detail:"web runtime"},{key:"web-manifest",detail:"web manifest"},{key:"service-worker-metadata",detail:"service worker metadata"},{key:"icons",detail:"icons"},{key:"offline-capability",detail:"offline capability metadata"});
  if (t==="web-game") capabilities.push({key:"canvas-runtime",detail:"canvas runtime"},{key:"asset-manifest",detail:"asset manifest"},{key:"game-loop",detail:"game loop metadata"},{key:"input-mapping",detail:"input mapping metadata"});
  if (t==="roblox") capabilities.push({key:"place-manifest",detail:"place manifest"},{key:"universe-metadata",detail:"universe metadata"},{key:"lua-compatibility",detail:"lua/roblox-ts compatibility"},{key:"asset-manifest",detail:"asset manifest"},{key:"publish-blocked",detail:"publish blocked"});
  if (t==="steam") capabilities.push({key:"desktop-runtime",detail:"desktop runtime"},{key:"depot-metadata",detail:"depot metadata"},{key:"store-capsule-assets",detail:"store capsule assets"},{key:"app-id-reference",detail:"app id placeholder/reference"},{key:"controller-input",detail:"controller input metadata"},{key:"publish-blocked",detail:"publish blocked"});
  const assetsByTarget: Record<UIPlatformTarget,string[]> = { ios:["icon-1024","icon-512","splash","app-store-metadata","privacy-policy-reference"], android:["icon-1024","icon-512","splash","app-store-metadata","privacy-policy-reference"], "mobile-web":["icon-512","icon-192","web-manifest","service-worker-metadata"], "desktop-web":["icon-512","icon-192","web-manifest","service-worker-metadata"], roblox:["place-thumbnail","game-icon","universe-metadata","asset-manifest"], steam:["capsule-main","capsule-small","library-hero","app-id-reference","depot-manifest"], "web-game":["game-thumbnail","asset-manifest","controls-mapping"], unknown:[] };
  const manifestByTarget: Record<UIPlatformTarget,string[]> = { ios:["identifier","permissions","displayName","version"], android:["identifier","permissions","displayName","version"], "mobile-web":["manifestName","startUrl","displayMode","icons"], "desktop-web":["manifestName","startUrl","displayMode","icons"], roblox:["universeIdReference","placeIdReference","experienceMetadata"], steam:["appIdReference","depotIdReference","launchOptions","storeMetadata"], "web-game":["canvasRootId","assetPreloadList","inputMap"], unknown:[] };
  return {capabilities, requiredAssets: assetsByTarget[t].map((a)=>({kind:a,required:true,reason:`Required for ${t}`})), manifestRequirements: manifestByTarget[t].map((m)=>({field:m,required:true,reason:`Required for ${t}`}))};
}
