import { type EditableUIDocument } from "./uiDocumentModel";
import { type UIDocumentDiff } from "./uiDocumentDiff";
export type UISourceSyncPlanOperationKind="updateComponentFile"|"addPageFile"|"removePageFile"|"updateThemeFile"|"updateRouteFile"|"updateBindingFile"|"manualReviewRequired";
export type UISourceSyncPlanOperation={kind:UISourceSyncPlanOperationKind; pageIds:string[]; nodeIds:string[]; targetFileHint?:string; reason?:string};
export type UISourceSyncPlan={operations:UISourceSyncPlanOperation[]; affectedPageIds:string[]; affectedNodeIds:string[]; caveat:string; success:boolean};
export const UI_SOURCE_SYNC_PLAN_CAVEAT="Source sync plan is dry-run/planning only and does not rewrite files or prove export/launch readiness.";
export function createUISourceSyncPlan(diff: UIDocumentDiff, document: EditableUIDocument, options?:{fileHints?:Record<string,string>}): UISourceSyncPlan { const ops:UISourceSyncPlanOperation[]=[]; for(const op of diff.operations){ if(op.kind==="pageAdded") ops.push({kind:"addPageFile",pageIds:[op.pageId!],nodeIds:[],targetFileHint:options?.fileHints?.[op.pageId!]}); else if(op.kind==="pageRemoved") ops.push({kind:"removePageFile",pageIds:[op.pageId!],nodeIds:[],targetFileHint:options?.fileHints?.[op.pageId!]}); else if(op.kind==="themeUpdated") ops.push({kind:"updateThemeFile",pageIds:[],nodeIds:[],targetFileHint:"theme.ts"}); else if(op.kind==="bindingUpdated") ops.push({kind:"updateBindingFile",pageIds:op.pageId?[op.pageId]:[],nodeIds:op.nodeId?[op.nodeId]:[]}); else if(["nodeAdded","nodeRemoved","nodeMoved","nodeUpdated","layoutUpdated","styleUpdated","textUpdated"].includes(op.kind)) ops.push({kind:"updateComponentFile",pageIds:op.pageId?[op.pageId]:[],nodeIds:op.nodeId?[op.nodeId]:[]}); }
 if(ops.some(o=>!o.targetFileHint && (o.kind==="updateComponentFile"||o.kind==="updateBindingFile"))) ops.push({kind:"manualReviewRequired",pageIds:diff.changedPageIds,nodeIds:diff.changedNodeIds,reason:"Ambiguous file mapping"});
 return {operations:ops, affectedPageIds:diff.changedPageIds, affectedNodeIds:diff.changedNodeIds, caveat:UI_SOURCE_SYNC_PLAN_CAVEAT, success:true}; }
export function validateUISourceSyncPlan(plan: Partial<UISourceSyncPlan>): {valid:boolean;issues:string[]} { const issues:string[]=[]; if(!Array.isArray(plan.operations)) issues.push("operations missing"); if(!plan.caveat?.includes("dry-run/planning only")) issues.push("caveat missing"); return {valid:issues.length===0,issues}; }
