import assert from "assert";
import fs from "fs";
const c = fs.readFileSync("apps/control-plane/src/components/live-ui-builder/LiveUIBuilderCommandInput.tsx", "utf8");
assert(c.includes("Enter a command first."));
assert(c.includes("setValue(\"\")"));
assert(c.includes("Could not parse command"));
assert(c.includes("const textareaId = \"live-ui-builder-command-input\""));
assert(c.includes("<label htmlFor={textareaId}>Live UI command</label>"));
assert(c.includes("<textarea id={textareaId}"));
console.log("liveUIBuilderCommandInput.test.ts passed");
