import assert from "assert";
import fs from "fs";
const panel = fs.readFileSync("apps/control-plane/src/components/live-ui-builder/LiveUIBuilderSourceSyncPanel.tsx", "utf8");
const hook = fs.readFileSync("apps/control-plane/src/components/vibe/useLiveUIBuilderVibe.ts", "utf8");
assert(panel.includes("Dry Run Source Sync"));
assert(panel.includes("Apply requires real file adapter"));
assert(panel.includes("project-root scoped"));
assert(panel.includes("Confirm guarded local write apply"));
assert(panel.includes("hasRealFileAdapter"));
assert(hook.includes("const [fileAdapter, setFileAdapter]"));
assert(hook.includes("configureLocalSourceAdapter"));
assert(hook.includes("sourceSyncApplyConfirmed"));
assert(!hook.includes('if (result.status === "applied") sourceSyncDryRun'));
assert(panel.includes("AST-aware dry run caveat"));
assert(panel.includes("Confidence:"));
assert(panel.includes("Source kinds:"));
assert(panel.includes("Identity coverage:"));
assert(panel.includes("Parser-backed source identity is best-effort and does not guarantee semantic runtime equivalence."));
assert(panel.includes("Blocked quality reason"));
assert(panel.includes("Route files to create"));
console.log("liveUIBuilderSourceSyncPanel.test.ts passed");
assert(panel.includes("Rollback requires server-side local adapter."));
assert(panel.includes("Multi-file plan id"));
assert(panel.includes("Changed file count"));
assert(panel.includes("Dependency count"));
assert(panel.includes("Risk level"));
assert(panel.includes("Multi-file planning is dry-run only and does not write files or prove runtime correctness."));
