import assert from "node:assert/strict";import fs from "node:fs";
const c=fs.readFileSync('apps/control-plane/src/components/live-ui-builder/LiveUIBuilderAppStructurePanel.tsx','utf8');
assert.ok(c.includes('App Structure'));assert.ok(c.includes('Source sync remains explicit and guarded'));
assert.ok(c.includes('needsResolution'));
assert.ok(c.includes('needsResolution && candidates.length > 0 ? candidates : appStructure?.pages'));
assert.ok(c.includes('reusableComponents?: ReusableComponent[]'));
assert.ok(c.includes('appStructure?.reusableComponents ?? appStructure?.components ?? []'));
assert.ok(c.includes('semanticRole'));assert.ok(c.includes('Select page'));assert.ok(c.includes('Reuse component'));
const h=fs.readFileSync('apps/control-plane/src/components/vibe/useLiveUIBuilderVibe.ts','utf8');assert.ok(!h.includes('source file writing'));
console.log('ok liveUIBuilderAppStructurePanel');
