import assert from "assert";
import fs from "fs";
const c = fs.readFileSync("apps/control-plane/src/components/vibe/LiveUIBuilderPreviewSurface.tsx", "utf8");
assert(c.includes("editableDocument"));
assert(c.includes("selectedNodeId"));
assert(c.includes("changedNodeIds"));
assert(c.includes("LiveUIBuilderDocumentRenderer"));
assert(c.includes("Document-driven preview, not final production rendering."));
assert(c.includes("no source rewrite/export/deploy claims"));
console.log("liveUIBuilderVibePreviewSurface.test.ts passed");
