import fs from "fs"; import path from "path"; import type { RepoValidatorResult } from "../repoValidators";
const has=(r:string,p:string)=>fs.existsSync(path.join(r,p)); const read=(r:string,p:string)=>fs.readFileSync(path.join(r,p),"utf8");
export function validateLiveUIBuilderVisualReadiness(root:string): RepoValidatorResult {
  const checks=["apps/control-plane/src/components/live-ui-builder/LiveUIBuilderDocumentRenderer.tsx","apps/control-plane/src/components/live-ui-builder/LiveUIBuilderInspectOverlay.tsx","apps/control-plane/src/components/vibe/LiveUIBuilderPreviewSurface.tsx","apps/control-plane/src/components/vibe/useLiveUIBuilderVibe.ts","packages/validation/src/tests/liveUIBuilderDocumentRenderer.test.ts","packages/validation/src/tests/liveUIBuilderInspectOverlay.test.ts","package.json","packages/validation/src/repoValidators.ts"];
  if(!checks.every(c=>has(root,c))) return {name:"Validate-Botomatic-LiveUIBuilderVisualReadiness",status:"failed",summary:"Required visual readiness files are missing.",checks};
  const renderer=read(root,checks[0]),overlay=read(root,checks[1]),surface=read(root,checks[2]),hook=read(root,checks[3]),pkg=JSON.parse(read(root,checks[6])) as {scripts?:Record<string,string>},validators=read(root,checks[7]);
  const scripts=pkg.scripts??{}; const universal=scripts["test:universal"]??"";
  const ok=renderer.includes("Document-driven preview, not final production rendering.")&&overlay.includes("data-selected")&&overlay.includes("data-changed")&&overlay.includes("data-selectable")&&surface.includes("editableDocument")&&surface.includes("selectedNodeId")&&surface.includes("changedNodeIds")&&hook.includes("editableDocument")&&hook.includes("selectedNodeId")&&hook.includes("selectNode")&&scripts["test:live-ui-builder-document-renderer"]&&scripts["test:live-ui-builder-inspect-overlay"]&&universal.includes("test:live-ui-builder-document-renderer")&&universal.includes("test:live-ui-builder-inspect-overlay")&&validators.includes("validateLiveUIBuilderVisualReadiness")&&!surface.toLowerCase().includes("export readiness")&&!surface.toLowerCase().includes("full source sync");
  return {name:"Validate-Botomatic-LiveUIBuilderVisualReadiness",status:ok?"passed":"failed",summary:ok?"Live UI builder visual readiness checks passed.":"Live UI builder visual readiness checks failed.",checks};
}
