import fs from "fs"; import path from "path"; import type { RepoValidatorResult } from "../repoValidators";
const has=(r:string,p:string)=>fs.existsSync(path.join(r,p)); const read=(r:string,p:string)=>fs.readFileSync(path.join(r,p),"utf8");
export function validateLiveUIBuilderInteractionReadiness(root:string): RepoValidatorResult {
  const checks=["packages/ui-preview-engine/src/uiPreviewInteractionState.ts","packages/ui-preview-engine/src/uiPreviewInteractionAdapter.ts","packages/ui-preview-engine/src/uiPreviewReviewPayload.ts","packages/ui-preview-engine/src/uiPreviewInteractionFixture.ts","packages/ui-preview-engine/src/tests/uiPreviewInteractionState.test.ts","packages/ui-preview-engine/src/tests/uiPreviewInteractionAdapter.test.ts","packages/ui-preview-engine/src/tests/uiPreviewReviewPayload.test.ts","packages/ui-preview-engine/src/tests/uiPreviewInteractionFixture.test.ts","packages/ui-preview-engine/src/index.ts","apps/control-plane/src/components/vibe/VibeDashboard.tsx","apps/control-plane/src/components/vibe/LiveUIBuilderPreviewSurface.tsx","package.json","packages/validation/src/repoValidators.ts"];
  if(!checks.every(c=>has(root,c))) return {name:"Validate-Botomatic-LiveUIBuilderInteractionReadiness",status:"failed",summary:"Required interaction wave files missing.",checks};
  const adapter=read(root,checks[1]),state=read(root,checks[0]),review=read(root,checks[2]),idx=read(root,checks[8]),vibeDashboard=read(root,checks[9]),previewSurface=read(root,checks[10]),pkg=read(root,checks[11]),validators=read(root,checks[12]);
  const ok=adapter.includes("typedChat")&&adapter.includes("spokenChat")&&adapter.includes("needsConfirmation")&&adapter.includes("needsResolution")&&adapter.toLowerCase().includes("planning-only source sync")&&state.includes("status")&&review.toLowerCase().includes("informational")&&idx.includes("uiPreviewInteractionAdapter")&&pkg.includes("test:ui-preview-interaction-adapter")&&pkg.includes("test:live-ui-builder-vibe-panel")&&pkg.includes("test:live-ui-builder-vibe-hook")&&pkg.includes("test:live-ui-builder-vibe-preview-surface")&&pkg.includes("test:universal")&&vibeDashboard.includes("LiveUIBuilderPreviewSurface")&&vibeDashboard.includes("disabled={!confirmationPending}")&&previewSurface.includes("live-ui-builder-preview-surface")&&validators.includes("validateLiveUIBuilderInteractionReadiness")&&!adapter.toLowerCase().includes("full source sync")&&!adapter.toLowerCase().includes("export/launch readiness claim")&&!adapter.toLowerCase().includes("full live visual ui builder completion");
  return {name:"Validate-Botomatic-LiveUIBuilderInteractionReadiness",status:ok?"passed":"failed",summary:ok?"Live UI builder interaction-contract readiness checks passed.":"Live UI builder interaction-contract readiness checks failed.",checks};
}
