import fs from "node:fs";import path from "node:path";import type { RepoValidatorResult } from "../contracts";
const has=(r:string,p:string)=>fs.existsSync(path.join(r,p));const read=(r:string,p:string)=>fs.readFileSync(path.join(r,p),"utf8");
export function validateLiveUIBuilderAppStructureReadiness(root:string): RepoValidatorResult {
 const checks=["packages/ui-preview-engine/src/uiAppStructureModel.ts","packages/ui-preview-engine/src/uiAppStructureCommands.ts","packages/ui-preview-engine/src/uiAppStructureMutation.ts","apps/control-plane/src/components/live-ui-builder/LiveUIBuilderAppStructurePanel.tsx","packages/ui-preview-engine/src/tests/uiAppStructureModel.test.ts","packages/ui-preview-engine/src/tests/uiAppStructureCommand.test.ts","packages/ui-preview-engine/src/tests/uiAppStructureMutation.test.ts","packages/validation/src/tests/liveUIBuilderAppStructurePanel.test.ts","package.json","packages/validation/src/repoValidators.ts"];
 if(!checks.every(c=>has(root,c))) return {name:"Validate-Botomatic-LiveUIBuilderAppStructureReadiness",status:"failed",summary:"Required app structure files are missing.",checks};
 const pkg=JSON.parse(read(root,'package.json')); const scripts=pkg.scripts??{}; const uni=scripts['test:universal']??''; const validators=read(root,'packages/validation/src/repoValidators.ts'); const hook=read(root,'apps/control-plane/src/components/vibe/useLiveUIBuilderVibe.ts');
 const model=read(root,'packages/ui-preview-engine/src/uiAppStructureModel.ts'); const commands=read(root,'packages/ui-preview-engine/src/uiAppStructureCommands.ts'); const mut=read(root,'packages/ui-preview-engine/src/uiAppStructureMutation.ts'); const mt=read(root,'packages/ui-preview-engine/src/tests/uiAppStructureMutation.test.ts'); const ct=read(root,'packages/ui-preview-engine/src/tests/uiAppStructureCommand.test.ts'); const ok=scripts['test:ui-app-structure-model']&&scripts['test:ui-app-structure-command']&&scripts['test:ui-app-structure-mutation']&&scripts['test:live-ui-builder-app-structure-panel']&&uni.includes('test:ui-app-structure-model')&&uni.includes('test:ui-app-structure-command')&&uni.includes('test:ui-app-structure-mutation')&&uni.includes('test:live-ui-builder-app-structure-panel')&&validators.includes('validateLiveUIBuilderAppStructureReadiness')&&hook.includes('sourceSync')&&hook.includes('runAppStructureCommand')&&model.includes('normalizeUIRoutePath')&&commands.includes('resolveUIPageReference')&&commands.includes('listUIPageTargetCandidates')&&model.includes('semanticRole')&&model.includes('usagePageIds')&&model.includes('claimBoundary')&&mt.includes('blocked')&&mt.includes('duplicate route path')&&ct.includes('needsResolution')&&!hook.toLowerCase().includes('source-write claims');
 return {name:"Validate-Botomatic-LiveUIBuilderAppStructureReadiness",status:ok?"passed":"failed",summary:ok?"Live UI builder app structure readiness checks passed.":"Live UI builder app structure readiness checks failed.",checks};
}
