import { Blueprint } from "../types";

export const androidKotlinApp: Blueprint = {
  id: "android_kotlin_app",
  name: "androidKotlinApp",
  category: "mobile android kotlin jetpack-compose native google play",
  description: "Native Android app built in Kotlin with Jetpack Compose — Google Play ready, follows Material You design guidelines, supports phones and tablets.",
  defaultPages: ["SplashScreen", "OnboardingScreen", "LoginScreen", "HomeScreen", "DetailScreen", "ProfileScreen", "SettingsScreen"],
  defaultComponents: ["BottomNavigationBar", "TopAppBar", "FloatingActionButton", "LazyColumn", "LoadingIndicator", "EmptyStateComposable", "ErrorComposable"],
  defaultRoles: ["guest", "user", "premium"],
  defaultPermissions: ["internet", "camera", "location", "post_notifications"],
  defaultEntities: ["User", "Session", "LocalData", "AppSettings"],
  defaultRelationships: ["User has_one AppSettings", "Session belongs_to User"],
  defaultWorkflows: [
    "app_launch_and_auth_check",
    "registration_and_login",
    "core_feature_navigation",
    "data_fetch_and_display",
    "settings_and_profile",
  ],
  defaultIntegrations: ["Firebase Auth", "Retrofit2 for REST", "Room for local DB", "WorkManager for background jobs", "DataStore for settings"],
  requiredQuestions: [
    "What is the minimum Android API level (minimum SDK version)?",
    "Does the app use Firebase Auth or a custom backend for authentication?",
    "Does the app need offline support with Room (local SQLite database)?",
    "Are WorkManager background jobs required?",
    "Does the app use Google Play Billing for in-app purchases?",
  ],
  safeAssumptions: [
    "Kotlin (latest stable) with Jetpack Compose for UI — no XML layouts",
    "MVVM architecture with ViewModel + StateFlow",
    "Kotlin Coroutines and Flow for all async operations — no RxJava",
    "Hilt (Dagger Hilt) for dependency injection",
    "Navigation Compose for in-app navigation with type-safe routes",
    "Retrofit2 + OkHttp3 + kotlinx.serialization for API calls",
    "DataStore (Proto or Preferences) for settings — no SharedPreferences",
    "EncryptedSharedPreferences or Android Keystore for secure token storage",
    "Room for local database if offline support required",
    "minSdk 26 (Android 8.0) as default minimum unless specified otherwise",
  ],
  riskyAssumptions: [
    "Google Play Store developer account and signing keystore",
    "Google Play Billing compliance for in-app purchases",
    "Android App Bundle (AAB) vs APK distribution decision",
    "ProGuard/R8 obfuscation rules for third-party libraries",
  ],
  recommendedStack: {
    frontend: "Jetpack Compose (Kotlin)",
    backend: "Retrofit2 + REST API (Firebase or custom Node.js)",
    jobs: "WorkManager + Kotlin Coroutines",
    deploy: "Gradle build → Google Play Console (AAB)",
  },
  acceptanceCriteria: [
    "App compiles with ./gradlew build without errors",
    "App runs on Android emulator (API 33+) without crashes",
    "Authentication flow completes with encrypted token storage",
    "Navigation between all screens works correctly",
    "Unit tests pass with ./gradlew test",
  ],
  launchCriteria: [
    "Signed release AAB with upload keystore",
    "App passes internal test track on Google Play Console",
    "Store listing (screenshots, description, privacy policy URL) complete",
    "Target API level meets current Google Play requirements",
    "No known crashes from Firebase Crashlytics in beta",
  ],
  validationRules: [
    "validateKotlinCompilation",
    "validateGradleBuild",
    "validateNoPlaceholders",
    "validateManifestPermissions",
  ],
  noPlaceholderRules: [
    "No TODO/FIXME in production Kotlin files",
    "No SharedPreferences for auth tokens — use EncryptedSharedPreferences or Keystore",
    "No hardcoded API URLs — use BuildConfig fields from gradle.properties",
    "No mock Retrofit services — all API interfaces must have real endpoint implementations",
  ],
};
