import { Blueprint } from "../types";

export const dotnetMauiApp: Blueprint = {
  id: "dotnet_maui_app",
  name: "dotnetMauiApp",
  category: "mobile desktop dotnet maui csharp windows ios android cross-platform microsoft",
  description: "Cross-platform app targeting iOS, Android, Windows, and macOS from a single C# codebase using .NET MAUI — enterprise-friendly, Windows-native on desktop.",
  defaultPages: ["SplashPage", "LoginPage", "MainPage", "SettingsPage", "DetailPage"],
  defaultComponents: ["Shell", "FlyoutMenu", "TabBar", "CollectionView", "ActivityIndicator", "RefreshView", "SearchBar"],
  defaultRoles: ["guest", "user", "admin"],
  defaultPermissions: ["internet", "camera", "location", "storage"],
  defaultEntities: ["User", "AppState", "LocalData", "SyncRecord"],
  defaultRelationships: ["User has_one AppState", "LocalData syncs_to RemoteData"],
  defaultWorkflows: [
    "app_launch_and_auth",
    "core_data_display",
    "offline_sync_workflow",
    "settings_management",
    "platform_specific_feature",
  ],
  defaultIntegrations: ["Microsoft.Identity.Client (MSAL)", "HttpClient for REST", "SQLite-net-pcl for local DB", "CommunityToolkit.Mvvm", "Essentials for device APIs"],
  requiredQuestions: [
    "Which platforms are required — iOS, Android, Windows, macOS, or all four?",
    "Does the app need Azure Active Directory / Entra ID authentication (MSAL)?",
    "Is this an enterprise app distributed via Intune/MDM or public app stores?",
    "Does the app need offline data sync with SQLite?",
    "Is there a .NET backend (ASP.NET) that the app will connect to?",
  ],
  safeAssumptions: [
    ".NET 8 (LTS) with C# 12",
    "MVVM architecture using CommunityToolkit.Mvvm (RelayCommand, ObservableObject)",
    "Shell navigation with route-based URI navigation",
    "HttpClient with BaseAddress and AuthenticationMessageHandler for API calls",
    "Microsoft.Extensions.DependencyInjection for DI (MauiProgram.cs)",
    "SQLite-net-pcl for local offline storage",
    "SecureStorage API (Essentials) for auth token persistence",
    "Platform-specific code via partial classes or #if WINDOWS / #if ANDROID",
  ],
  riskyAssumptions: [
    "Apple Developer account for iOS/macOS builds",
    "Windows code signing certificate",
    "Intune/MDM configuration for enterprise distribution",
    "MAUI BlazorWebView if mixing Blazor components",
  ],
  recommendedStack: {
    frontend: ".NET MAUI + C# (CommunityToolkit.Mvvm)",
    backend: "ASP.NET Core API or Azure Functions",
    jobs: "BackgroundService + WorkManager (Android) / BGTaskScheduler (iOS)",
    deploy: "dotnet publish → App Store / Play Store / Microsoft Store / Sideload",
  },
  acceptanceCriteria: [
    "dotnet build succeeds for all target frameworks",
    "App launches on Android emulator and Windows without errors",
    "Authentication flow with MSAL or email/password completes",
    "Navigation between all pages works on all platforms",
    "Data fetches from backend and displays correctly",
  ],
  launchCriteria: [
    "Platform-specific builds signed and tested (iOS, Android, Windows)",
    "App submitted to relevant stores or MDM portal",
    "All required permissions declared in platform manifests",
    "End-to-end tested on physical device for each platform",
    "No known crashes from App Center or custom telemetry",
  ],
  validationRules: [
    "validateDotnetBuild",
    "validateCSharpCompilation",
    "validateNoPlaceholders",
    "validateMauiManifests",
  ],
  noPlaceholderRules: [
    "No TODO/FIXME in production C# or XAML files",
    "No hardcoded credentials or API keys in source",
    "No Preferences API for auth tokens — use SecureStorage",
    "No mock HttpClient — all service classes must target real API endpoints",
  ],
};
