import { Blueprint } from "../types";

export const electronApp: Blueprint = {
  id: "electron_app",
  name: "electronApp",
  category: "desktop electron windows mac linux cross-platform native",
  description: "Cross-platform desktop application for Windows, macOS, and Linux built with Electron + React/TypeScript — native OS integration, auto-update, offline-capable.",
  defaultPages: ["MainWindow", "Settings", "About", "Onboarding"],
  defaultComponents: ["TitleBar", "Sidebar", "StatusBar", "ContextMenu", "DialogOverlay", "NotificationToast", "UpdateBanner"],
  defaultRoles: ["user", "admin"],
  defaultPermissions: ["read", "write", "system_access"],
  defaultEntities: ["AppState", "UserPreference", "LocalData", "UpdateRecord"],
  defaultRelationships: ["UserPreference belongs_to AppState", "LocalData syncs_to RemoteData"],
  defaultWorkflows: [
    "app_launch_and_init",
    "core_feature_workflow",
    "auto_update_check_and_install",
    "settings_management",
    "offline_mode_with_sync",
  ],
  defaultIntegrations: ["electron-updater (auto-update)", "electron-store (settings)", "electron-log", "IPC main/renderer bridge", "OS notifications via Electron API"],
  requiredQuestions: [
    "Which OS platforms must be supported — Windows only, macOS only, or all three (Win/Mac/Linux)?",
    "Does the app need to access local filesystem, system tray, or OS notifications?",
    "Is there a backend API the app talks to, or is it fully local/offline?",
    "Does the app require auto-update delivery (via GitHub Releases or S3)?",
    "Is this a paid app requiring license key validation?",
  ],
  safeAssumptions: [
    "Electron 30+ with context isolation enabled and nodeIntegration: false",
    "React + TypeScript for renderer process UI",
    "Vite as bundler for the renderer (not webpack)",
    "IPC bridge (preload.ts with contextBridge.exposeInMainWorld) for main↔renderer communication",
    "electron-builder for packaging (.exe, .dmg, .AppImage)",
    "electron-updater for auto-update via GitHub Releases or S3",
    "electron-store for local settings persistence",
    "Separate tsconfig.json for main process and renderer process",
    "Code signing required for macOS (notarization) and Windows (Authenticode)",
  ],
  riskyAssumptions: [
    "Code signing certificates (must be purchased/provisioned externally)",
    "macOS notarization requirements and Apple Developer account",
    "Windows Defender SmartScreen for unsigned builds",
    "GPU acceleration and hardware-specific rendering edge cases",
  ],
  recommendedStack: {
    frontend: "Electron renderer: React 18 + TypeScript + Vite",
    backend: "Electron main process (Node.js) + optional REST API",
    jobs: "Electron background workers via ipcMain + Worker threads",
    deploy: "electron-builder → GitHub Releases + auto-update via electron-updater",
  },
  acceptanceCriteria: [
    "App packages and launches on all target platforms without errors",
    "IPC communication between main and renderer works for all core operations",
    "Auto-update detects new version, downloads, and installs correctly",
    "Local settings persist between app restarts",
    "No unhandled promise rejections in main process",
  ],
  launchCriteria: [
    "Code-signed builds for Windows (.exe) and macOS (.dmg)",
    "macOS notarization passed",
    "Auto-update endpoint configured and tested",
    "App icon provided in all required sizes (512x512, 256x256, 128x128, 16x16)",
    "First-run onboarding completes without errors",
  ],
  validationRules: [
    "validateTypeScriptCompilation",
    "validateElectronBuild",
    "validateIPCBridge",
    "validateNoPlaceholders",
  ],
  noPlaceholderRules: [
    "No TODO/FIXME in production main or renderer process files",
    "No nodeIntegration: true — always use contextBridge",
    "No hardcoded file paths — use app.getPath() for user data directories",
    "No mock IPC handlers — all ipcMain.handle() must have real implementations",
  ],
};
