import { Blueprint } from "../types";

export const flutterApp: Blueprint = {
  id: "flutter_app",
  name: "flutterApp",
  category: "mobile flutter dart ios android cross-platform google",
  description: "Cross-platform mobile app (iOS + Android) built with Flutter and Dart — single codebase, native performance, Material and Cupertino UI support.",
  defaultPages: ["SplashScreen", "OnboardingScreen", "LoginScreen", "HomeScreen", "ProfileScreen", "SettingsScreen"],
  defaultComponents: ["BottomNavigationBar", "AppBar", "CustomTextField", "PrimaryButton", "LoadingIndicator", "EmptyStateWidget", "ErrorWidget"],
  defaultRoles: ["guest", "user", "admin"],
  defaultPermissions: ["read", "write", "notifications"],
  defaultEntities: ["User", "Session", "AppSettings", "CachedData"],
  defaultRelationships: ["User has_one AppSettings", "User has_many CachedData"],
  defaultWorkflows: [
    "splash_and_auth_check",
    "registration_and_login",
    "core_feature_navigation",
    "data_fetch_and_cache",
    "settings_and_profile",
  ],
  defaultIntegrations: ["Firebase Auth", "Firebase Firestore or REST API", "flutter_local_notifications", "shared_preferences", "go_router"],
  requiredQuestions: [
    "Which platforms — iOS, Android, or both? Any Web or Desktop targets?",
    "Does the app use Firebase or a custom backend API?",
    "What state management approach is preferred (Riverpod, Bloc, Provider)?",
    "Does the app need offline data caching?",
    "Are native platform features required (camera, GPS, biometrics, NFC)?",
  ],
  safeAssumptions: [
    "Dart (latest stable) as sole language",
    "Flutter 3.x SDK",
    "Riverpod 2 for state management (preferred over Provider or GetX)",
    "go_router for declarative routing with deep link support",
    "dio for HTTP client with interceptors for auth token injection",
    "flutter_secure_storage for auth token persistence",
    "freezed + json_serializable for immutable data classes and JSON parsing",
    "Material 3 design system (adaptive Cupertino components on iOS where needed)",
  ],
  riskyAssumptions: [
    "Platform channel / method channel usage for native code",
    "App Store review timeline and compliance",
    "Google Play billing / Apple IAP compliance",
    "Background processing limits (iOS background modes)",
  ],
  recommendedStack: {
    frontend: "Flutter + Dart (Riverpod, go_router)",
    backend: "Firebase or Node.js REST API",
    jobs: "Dart Isolates + flutter_local_notifications",
    deploy: "flutter build ipa/apk → App Store + Play Store",
  },
  acceptanceCriteria: [
    "App compiles and runs on both iOS and Android without errors",
    "Authentication flow works end-to-end with secure storage",
    "Navigation between all screens works without exceptions",
    "Data fetches correctly from backend and renders in UI",
    "No unhandled exceptions in Flutter error handler",
  ],
  launchCriteria: [
    "Production build passes flutter analyze with no errors",
    "App icons and splash screens configured for both platforms",
    "Privacy policy and app descriptions prepared for store listings",
    "Internal testing build distributed and approved",
    "No known P0 crashes from Crashlytics or Sentry",
  ],
  validationRules: [
    "validateDartCompilation",
    "validateFlutterAnalyze",
    "validateNoPlaceholders",
    "validateGoRouterSetup",
  ],
  noPlaceholderRules: [
    "No TODO/FIXME in production widget files",
    "No hardcoded backend URLs — use environment config via --dart-define",
    "No shared_preferences for auth tokens — use flutter_secure_storage",
    "No print() statements in production builds (use logger package)",
  ],
};
