import { Blueprint } from "../types";

export const godotGame: Blueprint = {
  id: "godot_game",
  name: "godotGame",
  category: "game godot gdscript indie open-source",
  description: "Cross-platform game built in Godot 4 with GDScript, featuring scene tree architecture, resource system, save/load, and export pipeline for PC/Web/Mobile.",
  defaultPages: ["MainMenu", "Gameplay", "PauseMenu", "Settings", "GameOver"],
  defaultComponents: ["HUD", "DialogueBox", "InventoryPanel", "OptionsMenu", "LoadingOverlay"],
  defaultRoles: ["player", "admin"],
  defaultPermissions: ["play", "configure"],
  defaultEntities: ["PlayerData", "GameState", "SaveData", "Resource", "Quest"],
  defaultRelationships: ["GameState contains PlayerData", "PlayerData has_many Quests", "SaveData serializes GameState"],
  defaultWorkflows: [
    "start_or_load_game",
    "core_gameplay_loop",
    "pause_and_settings",
    "save_game_to_disk",
    "scene_transition",
  ],
  defaultIntegrations: ["Godot Export Templates", "Steam via GodotSteam addon (optional)", "Web export via HTML5 template"],
  requiredQuestions: [
    "What genre is the game (platformer, RPG, top-down, puzzle, visual novel)?",
    "Which export targets are required (Windows, Mac, Linux, Web/HTML5, Android, iOS)?",
    "Is the game single-player or multiplayer?",
    "Does the game need Steam integration (achievements, leaderboards)?",
    "What is the primary scripting language (GDScript, C#, or both)?",
  ],
  safeAssumptions: [
    "Godot 4.x as the engine version",
    "GDScript as primary scripting language",
    "Scene tree architecture with Autoloads for global state (GameManager, AudioManager, SaveManager)",
    "Godot Resource (.tres/.res) system for data-driven content",
    "JSON save files via FileAccess for cross-platform portability",
    "Signal-based communication between nodes to avoid tight coupling",
    "Export templates pre-installed for target platforms",
  ],
  riskyAssumptions: [
    "Multiplayer transport choice (ENet vs WebRTC vs relay server)",
    "Godot C# vs GDScript performance tradeoffs for compute-heavy systems",
    "Mobile input and screen size adaptation",
    "Monetisation on mobile (IAP requires platform SDKs not native to Godot)",
  ],
  recommendedStack: {
    frontend: "Godot 4 Control nodes + CanvasLayer (GDScript)",
    backend: "Godot 4 Node-based game logic (GDScript) + optional REST backend",
    jobs: "Godot coroutines / await / AnimationPlayer for async flows",
    deploy: "Godot export pipeline + GitHub Actions for automated builds",
  },
  acceptanceCriteria: [
    "Project exports without errors for all target platforms",
    "Main menu → gameplay → save → load → quit cycle completes without crashes",
    "All scenes load without missing resource errors",
    "Save data persists correctly between sessions",
    "No GDScript runtime errors in the critical gameplay path",
  ],
  launchCriteria: [
    "Export templates set up and tested for each target platform",
    "itch.io or Steam build uploaded and playable",
    "No known P0 crashes in release export",
    "Performance tested at target frame rate on lowest-spec device",
    "All placeholder assets replaced with final content",
  ],
  validationRules: [
    "validateGDScriptSyntax",
    "validateGodotExportSuccess",
    "validateNoPlaceholders",
    "validateSceneIntegrity",
  ],
  noPlaceholderRules: [
    "No TODO/FIXME in production GDScript files",
    "No print() spam in release builds",
    "No missing resource references in scenes",
    "No mock save/load functions — must use FileAccess with real paths",
  ],
};
