import { Blueprint } from "../types";

export const iosSwiftApp: Blueprint = {
  id: "ios_swift_app",
  name: "iosSwiftApp",
  category: "mobile ios swift swiftui native apple iphone ipad",
  description: "Native iOS app built in Swift with SwiftUI — App Store ready, follows Apple Human Interface Guidelines, supports iPhone and iPad.",
  defaultPages: ["LaunchScreen", "OnboardingView", "LoginView", "HomeView", "DetailView", "ProfileView", "SettingsView"],
  defaultComponents: ["NavigationStack", "TabView", "CustomButton", "FormField", "LoadingView", "EmptyStateView", "ErrorView"],
  defaultRoles: ["guest", "user", "premium"],
  defaultPermissions: ["read", "write", "push_notifications", "camera", "location"],
  defaultEntities: ["User", "Session", "LocalCache", "AppSettings"],
  defaultRelationships: ["User has_one AppSettings", "Session belongs_to User"],
  defaultWorkflows: [
    "app_launch_and_auth_check",
    "registration_and_sign_in",
    "core_feature_flow",
    "push_notification_handling",
    "settings_and_profile_management",
  ],
  defaultIntegrations: ["Sign in with Apple", "CloudKit (optional)", "URLSession for REST API", "UserNotifications framework", "Keychain Services"],
  requiredQuestions: [
    "What iOS version is the minimum deployment target?",
    "Does the app use Sign in with Apple, email/password, or social login?",
    "Does the app require iCloud sync or CloudKit?",
    "Are any special entitlements needed (HealthKit, NFC, In-App Purchases)?",
    "Is the app iPhone only, iPad only, or Universal?",
  ],
  safeAssumptions: [
    "Swift 5.9+ with SwiftUI as primary UI framework",
    "MVVM architecture with @Observable (iOS 17+) or ObservableObject",
    "Swift Concurrency (async/await, Actor) — no callbacks or legacy completion handlers",
    "Keychain via KeychainAccess or SwiftKeychainWrapper for secure token storage",
    "URLSession with async/await for networking — no Alamofire dependency",
    "Codable + JSONDecoder for API response parsing",
    "Sign in with Apple required for App Store apps with social login",
    "XCTest for unit tests, XCUITest for UI automation",
    "Swift Package Manager for dependencies — no CocoaPods",
  ],
  riskyAssumptions: [
    "Apple Developer account and provisioning profiles required",
    "TestFlight distribution setup",
    "App Review compliance (privacy labels, permission strings)",
    "In-App Purchase compliance and server-side receipt validation",
  ],
  recommendedStack: {
    frontend: "SwiftUI (Swift 5.9+)",
    backend: "URLSession + REST API (backend built separately)",
    jobs: "Background App Refresh + BackgroundTasks framework",
    deploy: "Xcode Archive → App Store Connect → App Store",
  },
  acceptanceCriteria: [
    "App builds and runs on iOS simulator and real device without crashes",
    "Authentication flow completes with Keychain token storage",
    "All navigation flows work on both iPhone and iPad",
    "Push notifications received and displayed correctly",
    "App passes `xcodebuild test` for unit test suite",
  ],
  launchCriteria: [
    "App signed with Distribution certificate and provisioning profile",
    "Privacy usage description strings provided for all requested permissions",
    "App metadata (screenshots, description, keywords) submitted to App Store Connect",
    "TestFlight build approved by at least 5 beta testers",
    "No known crashes from crash reporting in beta",
  ],
  validationRules: [
    "validateSwiftCompilation",
    "validateXcodeBuild",
    "validateNoPlaceholders",
    "validatePrivacyStrings",
  ],
  noPlaceholderRules: [
    "No TODO/FIXME in production Swift files",
    "No UserDefaults for auth tokens — use Keychain",
    "No hardcoded API base URLs — use Configuration.plist or xcconfig",
    "No mock URLSession — use real networking with proper error handling",
  ],
};
