import { Blueprint } from "../types";

export const reactNativeApp: Blueprint = {
  id: "react_native_app",
  name: "reactNativeApp",
  category: "mobile react-native expo ios android cross-platform",
  description: "Cross-platform iOS and Android app built with React Native (Expo) — shared codebase, native APIs, App Store + Play Store ready.",
  defaultPages: ["Splash", "Onboarding", "Login", "Home", "Profile", "Settings"],
  defaultComponents: ["BottomTabBar", "StackNavigator", "FormInput", "PrimaryButton", "LoadingOverlay", "ErrorBoundary", "EmptyState"],
  defaultRoles: ["guest", "user", "admin"],
  defaultPermissions: ["read", "write", "push_notifications"],
  defaultEntities: ["User", "Session", "Notification", "UserPreference"],
  defaultRelationships: ["User has_many Sessions", "User has_many Notifications", "User has_one UserPreference"],
  defaultWorkflows: [
    "onboarding_and_registration",
    "login_and_auth",
    "core_feature_flow",
    "push_notification_delivery",
    "profile_management",
  ],
  defaultIntegrations: ["Expo Notifications", "Expo SecureStore", "Expo Camera", "AsyncStorage", "React Navigation"],
  requiredQuestions: [
    "Which platforms are required — iOS only, Android only, or both?",
    "Does the app need offline support with local data sync?",
    "What authentication method is required (email/password, social OAuth, biometric)?",
    "Does the app require push notifications?",
    "Will this be published to App Store and/or Play Store, or distributed as an enterprise build?",
  ],
  safeAssumptions: [
    "Expo managed workflow (EAS Build for production) — not bare React Native",
    "React Navigation 6 for all navigation (Stack + Bottom Tab)",
    "Expo SecureStore for token storage — never AsyncStorage for auth tokens",
    "TypeScript with strict mode throughout",
    "React Query or Zustand for server state and local state respectively",
    "NativeWind (Tailwind for RN) or StyleSheet API for styling",
    "Expo Router for file-based routing if using Expo SDK 50+",
    "EAS CLI for builds and OTA updates",
  ],
  riskyAssumptions: [
    "Native module requirements (may require bare workflow)",
    "App Store review timeline and compliance requirements",
    "Background location / health data permissions (platform-specific)",
    "Payment processing on mobile (Apple Pay, Google Pay, IAP compliance)",
  ],
  recommendedStack: {
    frontend: "React Native + Expo (TypeScript)",
    backend: "Node.js API (existing or new — mobile client only)",
    jobs: "Expo Background Fetch + Notifications",
    deploy: "EAS Build → App Store + Play Store",
  },
  acceptanceCriteria: [
    "App runs on both iOS simulator and Android emulator without crashes",
    "Authentication flow completes end-to-end with secure token storage",
    "Core feature works offline with optimistic updates where appropriate",
    "Push notifications received and displayed correctly",
    "No red-screen errors on any navigation path",
  ],
  launchCriteria: [
    "EAS build passes for both platforms",
    "App Store screenshots and metadata prepared",
    "Privacy policy URL configured for App Store",
    "TestFlight / internal test track approved",
    "No P0 crashes in beta testing",
  ],
  validationRules: [
    "validateTypeScriptCompilation",
    "validateExpoConfig",
    "validateNavigationSetup",
    "validateNoPlaceholders",
  ],
  noPlaceholderRules: [
    "No TODO/FIXME in production screens",
    "No hardcoded API URLs — use environment config via app.config.ts",
    "No AsyncStorage for auth tokens — use SecureStore",
    "No mock push notification handlers — must use real Expo notification service",
  ],
};
