import { Blueprint } from "../types";

export const robloxGame: Blueprint = {
  id: "roblox_game",
  name: "robloxGame",
  category: "game roblox luau metaverse",
  description: "Roblox game built in Luau with client/server architecture, DataStore persistence, RemoteEvents, and Roblox Studio conventions.",
  defaultPages: ["Lobby", "Gameplay", "Leaderboard", "Shop", "Settings"],
  defaultComponents: ["HUD", "InventoryFrame", "ShopGui", "LeaderboardGui", "NotificationBanner"],
  defaultRoles: ["player", "vip", "admin"],
  defaultPermissions: ["play", "purchase", "moderate"],
  defaultEntities: ["Player", "DataStore", "GameSession", "Inventory", "Transaction"],
  defaultRelationships: ["Player has_one Inventory", "GameSession belongs_to Player", "Transaction belongs_to Player"],
  defaultWorkflows: [
    "player_join_load_data",
    "gameplay_loop",
    "purchase_item_from_shop",
    "save_player_data_on_leave",
    "leaderboard_update",
  ],
  defaultIntegrations: ["Roblox DataStore API", "Roblox MarketplaceService", "Roblox Analytics"],
  requiredQuestions: [
    "What is the core gameplay loop (e.g. tycoon, obby, simulator, RPG, shooter)?",
    "Does the game use Developer Products, Game Passes, or both for monetization?",
    "What persistent player data must survive server restarts (currency, inventory, stats)?",
    "Does the game require real-time multiplayer sync between players on the same server?",
    "Are there admin commands or moderation tools needed?",
  ],
  safeAssumptions: [
    "Luau (Lua 5.1 superset) as the sole language",
    "Client/Server split: LocalScripts in StarterPlayerScripts, Scripts in ServerScriptService",
    "ProfileService or DataStore2 pattern for durable data persistence",
    "RemoteEvents and RemoteFunctions for client↔server communication",
    "ModuleScripts for shared logic (constants, utilities, data schemas)",
    "ReplicatedStorage for shared assets and RemoteEvents",
    "Roblox Studio project structure with standard service hierarchy",
  ],
  riskyAssumptions: [
    "Economy balance (currency earn rates, item prices)",
    "Anti-cheat strategy for exploiter mitigation",
    "Server size limits and cross-server data sync strategy",
    "Age-appropriate content rating and Roblox ToS compliance",
  ],
  recommendedStack: {
    frontend: "Roblox LocalScript + ScreenGui (Luau)",
    backend: "Roblox Script + ServerScriptService (Luau)",
    jobs: "Roblox BindableEvent / coroutine workers",
    deploy: "Roblox Studio → Roblox Platform publish",
  },
  acceptanceCriteria: [
    "Core gameplay loop runs without runtime errors",
    "Player data saves and loads correctly across sessions",
    "Shop purchases complete and grant items correctly",
    "Leaderboard updates on stat changes",
    "No exploitable RemoteEvent handlers (server-side validation on all remotes)",
  ],
  launchCriteria: [
    "Game passes and products configured in Creator Dashboard",
    "DataStore enabled and tested under load",
    "No Luau syntax errors or script errors in output",
    "Tested in Team Test with at least 2 players",
    "Content complies with Roblox Community Standards",
  ],
  validationRules: [
    "validateLuauSyntax",
    "validateServerSideRemoteValidation",
    "validateDataStorePersistence",
    "validateNoPlaceholders",
  ],
  noPlaceholderRules: [
    "No TODO/FIXME in production Luau scripts",
    "No print-only monetization handlers (must grant items)",
    "No unvalidated remote event handlers",
    "No hardcoded player UserId values",
  ],
};
