import { Blueprint } from "../types";

export const steamUnityGame: Blueprint = {
  id: "steam_unity_game",
  name: "steamUnityGame",
  category: "game unity steam csharp pc desktop indie",
  description: "PC/Steam game built in Unity with C#, featuring scene management, save system, Steam SDK integration, and production build pipeline.",
  defaultPages: ["MainMenu", "Gameplay", "PauseMenu", "Settings", "Credits", "LoadingScreen"],
  defaultComponents: ["HUD", "InventoryUI", "DialogueSystem", "MinimapController", "SaveLoadPanel"],
  defaultRoles: ["player", "admin"],
  defaultPermissions: ["play", "configure", "debug"],
  defaultEntities: ["PlayerData", "GameState", "SaveFile", "Achievement", "Settings"],
  defaultRelationships: ["GameState contains PlayerData", "PlayerData has_many Achievements", "SaveFile serializes GameState"],
  defaultWorkflows: [
    "new_game_or_load_save",
    "core_gameplay_loop",
    "pause_and_settings",
    "save_game",
    "unlock_achievement",
    "quit_to_main_menu",
  ],
  defaultIntegrations: [
    "Steamworks SDK (Achievements, Leaderboards, Cloud Save)",
    "Unity Input System",
    "Unity Addressables",
    "Unity Analytics (optional)",
  ],
  requiredQuestions: [
    "What genre is the game (platformer, RPG, puzzle, shooter, strategy)?",
    "Is this single-player, local co-op, or online multiplayer?",
    "What Unity version is being targeted?",
    "Which platforms are in scope for this build (Windows, Mac, Linux)?",
    "What are the Steam features needed (achievements, leaderboards, workshop, DLC)?",
  ],
  safeAssumptions: [
    "C# as sole script language (no UnityScript/Boo)",
    "Unity 2022 LTS or newer",
    "ScriptableObject-based data architecture for game config",
    "Scene-based game flow managed by a SceneLoader singleton",
    "JSON or binary serialisation for save files via Unity's built-in JsonUtility or Newtonsoft.Json",
    "Steamworks.NET wrapper for Steam SDK integration",
    "Assembly Definition files to keep compile times fast",
    "Editor tooling in a separate asmdef with UNITY_EDITOR guards",
  ],
  riskyAssumptions: [
    "Online multiplayer transport layer (Mirror vs Netcode vs Photon vs custom)",
    "Anti-cheat requirements for competitive modes",
    "DRM beyond Steam (GOG, Epic release plans)",
    "Console porting requirements (console cert compliance out of scope by default)",
  ],
  recommendedStack: {
    frontend: "Unity UI Toolkit or Unity uGUI (C#)",
    backend: "Unity C# game logic + optional Node.js backend for leaderboards/accounts",
    jobs: "Unity Coroutines / UniTask for async operations",
    deploy: "Steam Build Pipeline (steamcmd + depot upload) + CI via GitHub Actions",
  },
  acceptanceCriteria: [
    "Game builds without compiler errors for all target platforms",
    "Main menu → gameplay → pause → save → quit flow completes without exceptions",
    "Save and load preserves all critical game state",
    "Steam achievements unlock and sync correctly",
    "Frame rate meets target (60fps+ on recommended spec) in release build",
  ],
  launchCriteria: [
    "Steam store page and build depot configured",
    "Build submitted and accepted by Steam review",
    "No known P0/P1 crashes in final build",
    "Achievement icons and descriptions approved in Steamworks",
    "Pricing and regional pricing configured",
  ],
  validationRules: [
    "validateCSharpCompilation",
    "validateUnityBuildSuccess",
    "validateSteamIntegration",
    "validateNoPlaceholders",
  ],
  noPlaceholderRules: [
    "No TODO/FIXME in production C# scripts",
    "No Debug.Log spam in release builds (use conditional compilation)",
    "No hardcoded Steam App IDs in source (use config/env)",
    "No mock save handlers — must write real files",
  ],
};
