import { Blueprint } from "../types";

export const tauriApp: Blueprint = {
  id: "tauri_app",
  name: "tauriApp",
  category: "desktop tauri rust windows mac linux lightweight native",
  description: "Lightweight cross-platform desktop app built with Tauri (Rust backend) + React/TypeScript frontend — smaller binaries than Electron, native performance, system tray, OS APIs.",
  defaultPages: ["MainWindow", "Settings", "Dashboard"],
  defaultComponents: ["TitleBar", "Sidebar", "StatusBar", "SystemTrayMenu", "DialogOverlay", "UpdateNotice"],
  defaultRoles: ["user", "admin"],
  defaultPermissions: ["read", "write", "filesystem"],
  defaultEntities: ["AppState", "UserPreference", "LocalRecord"],
  defaultRelationships: ["UserPreference belongs_to AppState"],
  defaultWorkflows: [
    "app_launch_and_window_setup",
    "core_feature_workflow",
    "tauri_command_invoke",
    "filesystem_read_write",
    "system_tray_interaction",
  ],
  defaultIntegrations: ["Tauri Plugin Filesystem", "Tauri Plugin Notification", "Tauri Plugin Updater", "Tauri Plugin Shell", "Tauri Plugin Store"],
  requiredQuestions: [
    "Which OS platforms — Windows, macOS, Linux, or all three?",
    "Does the app need native filesystem access beyond the app sandbox?",
    "Is Rust experience available on the team, or should Rust backend be minimal?",
    "Does the app need a system tray icon with context menu?",
    "Is auto-update required (via Tauri Updater plugin)?",
  ],
  safeAssumptions: [
    "Tauri 2.x with Rust 2021 edition backend",
    "React 18 + TypeScript for frontend (Vite bundler)",
    "Tauri commands (Rust #[tauri::command]) for all frontend→backend calls",
    "tauri.conf.json with minimal allowlist — only declare permissions actually needed",
    "Tauri Plugin Store for key-value settings persistence",
    "Tauri Plugin Updater for auto-update (GitHub Releases as update server)",
    "@tauri-apps/api for all Tauri JS bindings — never use Node.js APIs in renderer",
    "CSP configured in tauri.conf.json to prevent XSS in renderer",
  ],
  riskyAssumptions: [
    "Rust compile times (first build is slow — ~5min)",
    "Code signing for macOS and Windows (requires external certs)",
    "Complex Rust backend logic (keep Rust thin — move logic to TypeScript where possible)",
    "Cross-compilation from CI (requires OS-specific runners)",
  ],
  recommendedStack: {
    frontend: "React 18 + TypeScript + Vite (renderer)",
    backend: "Rust (Tauri main process) — thin command layer only",
    jobs: "Tauri async commands + tokio for Rust async",
    deploy: "tauri build → GitHub Releases + Tauri Updater",
  },
  acceptanceCriteria: [
    "cargo build and npm run tauri build succeed on all target platforms",
    "All Tauri commands callable from renderer return correct results",
    "Filesystem read/write works within declared permissions",
    "Auto-update flow detects and applies new version",
    "No Rust panics in normal operation",
  ],
  launchCriteria: [
    "Signed builds for Windows and macOS",
    "macOS notarization passed",
    "App icon in all required sizes (app.png at 512x512 minimum)",
    "tauri.conf.json allowlist restricted to minimum required permissions",
    "Auto-update endpoint tested with a real version bump",
  ],
  validationRules: [
    "validateRustCargoCheck",
    "validateTypeScriptCompilation",
    "validateTauriBuild",
    "validateNoPlaceholders",
  ],
  noPlaceholderRules: [
    "No TODO/FIXME in Rust command handlers or renderer code",
    "No wildcard Tauri allowlist — all permissions must be explicit",
    "No use of Node.js APIs in renderer — use @tauri-apps/api only",
    "No mock Tauri command implementations — all commands must have real Rust handlers",
  ],
};
