import assert from "assert";
import { createUIExportBundleManifest } from "../uiExportBundlePlanner";
const one=createUIExportBundleManifest({sourceFiles:{"src\\a.ts":"a","src/b.ts":"bb"},fullProjectGenerationPlan:{files:[{path:"dist/app.js",referenceOnly:true}]},sourcePatchPlan:{operations:[{target:{filePath:"src/c.ts"}}]}});
const two=createUIExportBundleManifest({sourceFiles:{"src/a.ts":"a","src/b.ts":"bb"},fullProjectGenerationPlan:{files:[{path:"dist/app.js",referenceOnly:true}]},sourcePatchPlan:{operations:[{target:{filePath:"src/c.ts"}}]}});
assert.equal(one.bundleManifestId,two.bundleManifestId);assert.deepEqual(one.files.map(f=>f.filePath),[...one.files.map(f=>f.filePath)].sort());assert.equal(one.totalBytes,3);
assert(createUIExportBundleManifest({sourceFiles:{"/abs.ts":"x"}}).issues.some(i=>i.message.includes("Unsafe path")));
assert(createUIExportBundleManifest({sourceFiles:{"../x.ts":"x"}}).issues.length>0);
assert(createUIExportBundleManifest({sourceFiles:{".env":"x"}}).issues.length>0);
assert(createUIExportBundleManifest({sourceFiles:{"secret/private.key":"x"}}).issues.length>0);
assert(createUIExportBundleManifest({sourceFiles:{"node_modules/x":"x"}}).issues.length>0);
assert(createUIExportBundleManifest({fullProjectGenerationPlan:{files:[{path:"src/x.ts"}]}}).issues.some(i=>i.code==="missing-source-proof"));
console.log("uiExportBundlePlanner.test.ts passed");
