import assert from "assert";
import { createReactSourcePatchFromUIDiff } from "../uiReactSourcePatch";
const mapping:any={targets:[{sourceId:"p",filePath:"app/page.tsx"}],manualReviewRequired:[]};
const analysis:any=[{filePath:"app/page.tsx",isRouteFile:true}];
const sourceFiles={"app/page.tsx":"export default function Page(){ return <main><h1>Old</h1></main>; }"};
const safe=createReactSourcePatchFromUIDiff({changeType:"replaceTextLiteral",beforeSnippet:"a",afterSnippet:"b"},mapping,analysis,{sourceFiles});
assert.strictEqual(safe.operations[0].confidence,"high");
assert.ok(Boolean(safe.operations[0].sourceIdentityId));
assert.strictEqual(safe.operations[0].identityConfidence,"high");
const unsafe=createReactSourcePatchFromUIDiff({changeType:"replaceTextLiteral"},mapping,analysis,{});
assert.ok(unsafe.operations[0].requiresManualReview);
assert.ok(String(unsafe.operations[0].manualReviewReason).includes("missing source identity"));
const removeSafe=createReactSourcePatchFromUIDiff({changeType:"removeJsxNode",identityMarker:"data-identity",beforeSnippet:"<h1>Old</h1>"},mapping,analysis,{sourceFiles});
assert.strictEqual(removeSafe.operations[0].kind,"removeText");
const route=createReactSourcePatchFromUIDiff({changeType:"createPageRoute",targetFilePath:"app/new/page.tsx"},mapping,analysis,{});
assert.strictEqual(route.operations[0].sourceIdentityId,"created-file:app/new/page.tsx");
console.log("uiReactSourcePatch tests passed");
