import assert from "assert";
import fs from "fs";
import path from "path";
import { createUILocalFileAdapter } from "../uiLocalFileAdapter";
import { createUISourceApplyTransaction, applyUISourceTransaction, rollbackUISourceTransaction } from "../uiSourceApplyTransaction";
import { createLocalApplyFixture } from "./fixtures/localApplyFixture";

const fixture = createLocalApplyFixture();
const patch:any = { operations:[{kind:"replaceText",targetFilePath:"components/Hero.tsx",pageIds:["p"],nodeIds:["n"],beforeSnippet:"Hero",afterSnippet:"export function Hero(){return <section>Hero Updated</section>;}",confidence:"high",requiresManualReview:false,sourceKind:"react"},{kind:"createFile",targetFilePath:"app/new.tsx",pageIds:["p"],nodeIds:["n"],afterSnippet:"export default function New(){return null}",confidence:"high",requiresManualReview:false,sourceKind:"react"}],changedFiles:["components/Hero.tsx","app/new.tsx"],caveat:"Patch is a proposed source edit plan and does not prove runtime correctness or deployment readiness."};
const dryAdapter = createUILocalFileAdapter({ projectRoot: fixture.root, allowWrites: false });
const txDry = createUISourceApplyTransaction(patch,dryAdapter,{projectRoot:fixture.root,mode:"dryRun",idSeed:"a",context:"ctx"});
assert.equal(applyUISourceTransaction(txDry,{adapter:dryAdapter}).writesPerformed,0);
const writeAdapter = createUILocalFileAdapter({ projectRoot: fixture.root, allowWrites: true });
const tx = createUISourceApplyTransaction(patch,writeAdapter,{projectRoot:fixture.root,mode:"confirmedApply",idSeed:"a",context:"ctx",confirmationMarker:true});
assert(tx.beforeSnapshot.some((s)=>s.filePath==="app/new.tsx"&&!s.existedBefore));
assert(!applyUISourceTransaction(tx,{adapter:writeAdapter}).ok);
const apply = applyUISourceTransaction(tx,{adapter:writeAdapter,confirmationMarker:true});
assert(apply.ok);
assert.equal(apply.writesPerformed,2);
const rollback = rollbackUISourceTransaction(tx, writeAdapter);
assert(rollback.ok);
assert.equal(fs.existsSync(path.join(fixture.root,"app/new.tsx")), false);
assert.equal(fs.readFileSync(path.join(fixture.root,"components/Hero.tsx"),"utf8").includes("Hero</section>"), true);
const lowPatch:any = { ...patch, operations:[{...patch.operations[0], confidence:"low"}] };
assert(!applyUISourceTransaction(createUISourceApplyTransaction(lowPatch,writeAdapter,{projectRoot:fixture.root,mode:"confirmedApply"}),{adapter:writeAdapter,confirmationMarker:true}).ok);
const missBefore:any = { ...patch, operations:[{...patch.operations[0], kind:"replaceText", beforeSnippet:undefined}] };
assert(!applyUISourceTransaction(createUISourceApplyTransaction(missBefore,writeAdapter,{projectRoot:fixture.root,mode:"confirmedApply"}),{adapter:writeAdapter,confirmationMarker:true}).ok);
assert(!applyUISourceTransaction(tx,{adapter:dryAdapter,confirmationMarker:true}).ok);
assert(!rollbackUISourceTransaction({ ...tx, beforeSnapshot:[{ filePath:"../evil.ts", existedBefore:true, beforeContent:"x"}]}, writeAdapter).ok);
assert(!rollbackUISourceTransaction({ ...tx, beforeSnapshot:[{ filePath:"release-evidence/runtime/x.ts", existedBefore:true, beforeContent:"x"}]}, writeAdapter).ok);
console.log("uiSourceApplyTransaction tests passed");
