apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: runtime-spine
spec:
  rules:
    - host: runtime-spine.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: runtime-spine
                port:
                  number: 80
